return {
	-- {
	-- 	"ellisonleao/gruvbox.nvim",
	-- 	priority = 1000,
	-- 	config = true,
	-- 	opts = ...
	-- },
	-- {
	-- 	"sainnhe/gruvbox-material",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.g.gruvbox_material_background = "hard" -- hard, medium, soft, none
	-- 		vim.cmd.colorscheme("gruvbox-material")
	-- 	end,
	-- },
	-- {
	-- 	'sainnhe/sonokai',
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd.colorscheme('sonokai')
	-- 	end,
	-- },
	-- {
	-- 	'sainnhe/edge',
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		vim.cmd.colorscheme('edge')
	-- 	end,
	-- },
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 }, -- colorscheme init is in nvim/lua/theprimeagen/init.lua
	-- {
	-- 	"rebelot/kanagawa.nvim",
	-- 	-- lazy= false,
	-- 	config = function()
	-- 		vim.cmd("colorscheme kanagawa")
	-- 		-- vim.cmd("colorscheme kanagawa-dragon")
	-- 		-- vim.cmd("colorscheme kanagawa-wave")
	-- 	end
	-- }
}
